### ISSUE TITLE
Half modules dont work, binding some shit crashes 

### ISSUE THREAD

**Issue by Zane2b2t** [maywr/RusherHack#4]
and worst of all... translator doesnt work :scream: 
Please fix :pray: this is 1% better than future 2.9 crack :rofl:

**Comment by Spritzerland** [comment]
bruh this a rat it grabs your token 💀

**Comment by Zane2b2t** [comment]
> 

:nerd_face:

**Comment by kisman2000** [comment]
hello zane

**Comment by Zane2b2t** [comment]
> 

oh lmao
